# Generated by Django 6.0.3 on 2026-04-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumetemplate',
            name='image_url',
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='button_color',
            field=models.CharField(max_length=20),
        ),
    ]
