# Generated by Django 6.0.3 on 2026-05-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_additionaldetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='summary',
            field=models.TextField(default='Please update your summary.'),
            preserve_default=False,
        ),
    ]
