# Generated by Django 6.0.3 on 2026-05-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_canvasresume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanvasResume',
        ),
    ]
