# Generated by Django 6.0.3 on 2026-05-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_savedresume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedResume',
        ),
    ]
