# Generated by Django 6.0.3 on 2026-05-27 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_savedresume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Modern Minimalist, Tech Corporate', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short detail about layout focus.', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cl_templates/thumbnails/')),
                ('file_path', models.CharField(help_text='The internal template file path, e.g., cl_layouts/modern.html', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedCoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Cover Letter', help_text='Internal title name for dashboard tracking', max_length=255)),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('sender_location', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_name', models.CharField(blank=True, help_text='e.g., Hiring Manager, HR Team', max_length=150, null=True)),
                ('company_name', models.CharField(max_length=150)),
                ('job_title', models.CharField(help_text="The designation you're targeted towards", max_length=150)),
                ('letter_body', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.coverlettertemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
    ]
