# Generated by Django 6.0.3 on 2026-05-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_coverlettertemplate_savedcoverletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcoverletter',
            name='signature_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
